function signal_on()
    signal_1(true)
    signal_2(true)
    signal_3(true)
    signal_4(true)
    signal_5(true)
    signal_6(true)
end

function signal_1(enable)
    modelBase1=sim.getObjectHandle(sim.handle_self)
    modelName1=sim.getObjectName(modelBase1)
    if enable then
        sim.setIntegerSignal(modelName1 .."call_1",1)
    else
        sim.setIntegerSignal(modelName1 .."call_1",0)
    end
end

function signal_2(enable)
    modelBase2=sim.getObjectHandle(sim.handle_self)
    modelName2=sim.getObjectName(modelBase2)
    if enable then
        sim.setIntegerSignal(modelName2 .."call_2",1)
    else
        sim.setIntegerSignal(modelName2 .."call_2",0)
    end
end

function signal_3(enable)
    modelBase3=sim.getObjectHandle(sim.handle_self)
    modelName3=sim.getObjectName(modelBase3)
    if enable then
        sim.setIntegerSignal(modelName3 .."call_3",1)
    else
        sim.setIntegerSignal(modelName3 .."call_3",0)
    end
end

function signal_4(enable)
    modelBase4=sim.getObjectHandle(sim.handle_self)
    modelName4=sim.getObjectName(modelBase4)
    if enable then
        sim.setIntegerSignal(modelName4 .."call_4",1)
    else
        sim.setIntegerSignal(modelName4 .."call_4",0)
    end
end

function signal_5(enable)
    modelBase5=sim.getObjectHandle(sim.handle_self)
    modelName5=sim.getObjectName(modelBase5)
    if enable then
        sim.setIntegerSignal(modelName5 .."call_5",1)
    else
        sim.setIntegerSignal(modelName5 .."call_5",0)
    end
end

function signal_6(enable)


    modelBase6=sim.getObjectHandle(sim.handle_self)
    modelName6=sim.getObjectName(modelBase6)
    if enable then
        sim.setIntegerSignal(modelName6 .."call_6",1)
    else
        sim.setIntegerSignal(modelName6 .."call_6",0)
    end
end


function sysCall_threadmain()
    on=true
    joint01=sim.getObjectHandle('X')
    joint02=sim.getObjectHandle('Y')
    joint03=sim.getObjectHandle('Z')
    jointr=sim.getObjectHandle('Rotate')
    tt=1.2
    long_t=1.7
    long_long_t=3.2
    aty=0
    setx=0.5
    setpx=-0.5
    sety=-0.16
    setpy=-0.16
    pick_h1=0.0645
    pick_h2=0.134
    pick_h3=0.2025
    pick_h4=0.2768
    fall_h4=0.26
    fall_h3=0.18
    fall_h2=0.12
    fall_h1=0.05
    fall_h4_up=0.12
    fall_h3_up=0.05
    while (on==true) do
        signal_1(true)
        sim.setJointTargetPosition(joint01,setx) --pick_1
        sim.setJointTargetPosition(joint02,sety)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h1)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,60*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx+0.05) --pick_2 h2-h2-
        sim.setJointTargetPosition(joint02,sety-0.05)
        sim.wait(tt)
        signal_2(true)
        sim.setJointTargetPosition(joint03,aty-pick_h2)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,120*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx+0.05) --pick_3
        sim.setJointTargetPosition(joint02,sety+0.05)
        sim.wait(tt)
        signal_3(true)
        sim.setJointTargetPosition(joint03,aty-pick_h2)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,180*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx-0.05) --pick_4
        sim.setJointTargetPosition(joint02,sety+0.05)
        sim.wait(tt)
        signal_4(true)
        sim.setJointTargetPosition(joint03,aty-pick_h2)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,240*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx-0.05) --pick_5
        sim.setJointTargetPosition(joint02,sety-0.05)
        sim.wait(tt)
        signal_5(true)
        sim.setJointTargetPosition(joint03,aty-pick_h2)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,300*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx+0.1) --pick_6 h3-h3
        sim.setJointTargetPosition(joint02,sety+0.1)
        sim.wait(tt)
        signal_6(true)
        sim.setJointTargetPosition(joint03,aty-pick_h3)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,0)
        sim.wait(long_t)
        -----------------------------------------------------------
        sim.setJointTargetPosition(joint01,setpx-0.15)--fall 1
        sim.wait(long_long_t)
        sim.setJointTargetPosition(joint02,setpy+0.15)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4)
        sim.wait(tt)
        signal_1(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4_up)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,60*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx-0.15)--fall 2
        sim.setJointTargetPosition(joint02,setpy+0.05)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4)
        sim.wait(tt)
        signal_2(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4_up)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,120*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx-0.15)--fall 3
        sim.setJointTargetPosition(joint02,setpy-0.05)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4)
        sim.wait(tt)
        signal_3(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4_up)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,180*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx-0.15)--fall 4
        sim.setJointTargetPosition(joint02,setpy-0.15)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4)
        sim.wait(tt)
        signal_4(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4_up)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,240*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx-0.05)--fall 5
        sim.setJointTargetPosition(joint02,setpy-0.15)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4)
        sim.wait(tt)
        signal_5(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4_up)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,300*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx-0.05)--fall 6
        sim.setJointTargetPosition(joint02,setpy-0.05)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4)
        sim.wait(tt)
        signal_6(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx) 
        sim.setJointTargetPosition(joint02,sety)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,0)
        -----------------------------------------------------------
        sim.setJointTargetPosition(joint01,setx+0.1) --pick_7
        sim.setJointTargetPosition(joint02,sety)
        signal_1(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h3)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,60*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx+0.1) --pick_8
        sim.setJointTargetPosition(joint02,sety-0.1)
        signal_2(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h3)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,120*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx) --pick_9
        sim.setJointTargetPosition(joint02,sety-0.1)
        signal_3(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h3)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,180*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx) --pick_10
        sim.setJointTargetPosition(joint02,sety)
        signal_4(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h3)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,240*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx) --pick_11
        sim.setJointTargetPosition(joint02,sety+0.1)
        signal_5(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h3)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,300*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx-0.1) --pick_12
        sim.setJointTargetPosition(joint02,sety+0.1)
        signal_6(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h3)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,0)
        sim.wait(long_t)
         -----------------------------------------------------------
        sim.setJointTargetPosition(joint01,setpx-0.05)--fall 7
        sim.wait(tt)
        sim.setJointTargetPosition(joint02,setpy+0.05)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4)
        sim.wait(tt)
        signal_1(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4_up)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,60*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx-0.05)--fall 8
        sim.setJointTargetPosition(joint02,setpy+0.15)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4)
        sim.wait(tt)
        signal_2(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-0.12)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,120*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx+0.05)--fall 9
        sim.setJointTargetPosition(joint02,setpy+0.15)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4)
        sim.wait(tt)
        signal_3(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4_up)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,180*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx+0.05)--fall 10
        sim.setJointTargetPosition(joint02,setpy+0.05)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4)
        sim.wait(tt)
        signal_4(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4_up)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,240*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx+0.05)--fall 11
        sim.setJointTargetPosition(joint02,setpy-0.05)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4)
        sim.wait(tt)
        signal_5(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4_up)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,300*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx+0.05)--fall 12
        sim.setJointTargetPosition(joint02,setpy-0.15)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4)
        sim.wait(tt)
        signal_6(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx) 
        sim.setJointTargetPosition(joint02,sety)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,0)
        -----------------------------------------------------------
        sim.setJointTargetPosition(joint01,setx-0.1) --pick_13
        sim.setJointTargetPosition(joint02,sety)
        signal_1(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h3)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,60*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx-0.1) --pick_14 
        sim.setJointTargetPosition(joint02,sety-0.1)
        signal_2(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h3)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,120*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx-0.15) --pick_15 --h4-h4
        sim.setJointTargetPosition(joint02,sety+0.15)
        signal_3(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h4)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,180*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx-0.15) --pick_16
        sim.setJointTargetPosition(joint02,sety+0.05)
        signal_4(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h4)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,240*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx-0.15) --pick_17
        sim.setJointTargetPosition(joint02,sety-0.05)
        signal_5(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h4)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,300*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx-0.15) --pick_18
        sim.setJointTargetPosition(joint02,sety-0.15)
        signal_6(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h4)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,0)
        sim.wait(tt)
        sim.wait(long_t)
         -----------------------------------------------------------
        sim.setJointTargetPosition(joint01,setpx+0.15)--fall 13
        sim.wait(tt)
        sim.setJointTargetPosition(joint02,setpy-0.15)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4)
        sim.wait(tt)
        signal_1(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4_up)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,60*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx+0.15)--fall 14
        sim.setJointTargetPosition(joint02,setpy-0.05)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4)
        sim.wait(tt)
        signal_2(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4_up)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,120*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx+0.15)--fall 15
        sim.setJointTargetPosition(joint02,setpy+0.05)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4)
        sim.wait(tt)
        signal_3(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4_up)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,180*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx+0.15)--fall 16
        sim.setJointTargetPosition(joint02,setpy+0.15)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4)
        sim.wait(tt)
        signal_4(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4_up)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,240*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx+0.1)--fall 17 h3--h3
        sim.setJointTargetPosition(joint02,setpy-0.1)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h3)
        sim.wait(tt)
        signal_5(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h3_up)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,300*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx+0.1)--fall 18
        sim.setJointTargetPosition(joint02,setpy-0)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h3)
        sim.wait(tt)
        signal_6(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx) 
        sim.setJointTargetPosition(joint02,sety)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,0)
        sim.wait(tt)
        -----------------------------------------------------------
        sim.setJointTargetPosition(joint01,setx-0.05) --pick_19
        sim.setJointTargetPosition(joint02,sety-0.15)
        signal_1(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h4)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,60*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx-0.05) --pick_20 
        sim.setJointTargetPosition(joint02,sety-0.05)
        signal_2(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h4)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,120*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx-0.05) --pick_21
        sim.setJointTargetPosition(joint02,sety+0.05)
        signal_3(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h4)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,180*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx-0.05) --pick_22
        sim.setJointTargetPosition(joint02,sety+0.15)
        signal_4(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h4)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,240*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx+0.05) --pick_23
        sim.setJointTargetPosition(joint02,sety+0.15)
        signal_5(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h4)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,300*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx+0.05) --pick_24
        sim.setJointTargetPosition(joint02,sety+0.05)
        signal_6(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h4)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,0*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,0*math.pi/180)
        sim.wait(long_t)
         -----------------------------------------------------------
        sim.setJointTargetPosition(joint01,setpx+0.1)--fall 19
        sim.wait(tt)
        sim.setJointTargetPosition(joint02,setpy+0.1)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h3)
        sim.wait(tt)
        signal_1(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h3_up)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,60*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx)--fall 20
        sim.setJointTargetPosition(joint02,setpy+0.1)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h3)
        sim.wait(tt)
        signal_2(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h3_up)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,120*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx)--fall 21
        sim.setJointTargetPosition(joint02,setpy)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h3)
        sim.wait(tt)
        signal_3(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h3_up)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,180*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx)--fall 22
        sim.setJointTargetPosition(joint02,setpy-0.1)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h3)
        sim.wait(tt)
        signal_4(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h3_up)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,240*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx-0.1)--fall 23
        sim.setJointTargetPosition(joint02,setpy-0.1)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h3)
        sim.wait(tt)
        signal_5(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h3_up)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,300*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx-0.1)--fall 24
        sim.setJointTargetPosition(joint02,setpy-0)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h3)
        sim.wait(tt)
        signal_6(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx) 
        sim.setJointTargetPosition(joint02,sety)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,0*math.pi/180)
        -----------------------------------------------------------
        sim.setJointTargetPosition(joint01,setx+0.05) --pick_25
        sim.setJointTargetPosition(joint02,sety-0.05)
        signal_1(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h4)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,60*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx+0.05) --pick_26 
        sim.setJointTargetPosition(joint02,sety-0.15)
        signal_2(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h4)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,120*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx+0.15) --pick_27
        sim.setJointTargetPosition(joint02,sety-0.15)
        signal_3(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h4)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,180*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx+0.15) --pick_28
        sim.setJointTargetPosition(joint02,sety-0.05)
        signal_4(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h4)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,240*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx+0.15) --pick_29
        sim.setJointTargetPosition(joint02,sety+0.05)
        signal_5(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h4)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,300*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx+0.15) --pick_30
        sim.setJointTargetPosition(joint02,sety+0.15)
        signal_6(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h4)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,0*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,0*math.pi/180)
        sim.wait(long_long_t)
         -----------------------------------------------------------
        sim.setJointTargetPosition(joint01,setpx-0.1)--fall 25
        sim.wait(long_long_t)
        sim.setJointTargetPosition(joint02,setpy+0.1)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h3)
        sim.wait(tt)
        signal_1(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h3_up)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,60*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx-0.05)--fall 26
        sim.setJointTargetPosition(joint02,setpy+0.05)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h2)
        sim.wait(tt)
        signal_2(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,120*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx-0.05)--fall 27
        sim.setJointTargetPosition(joint02,setpy-0.05)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h2)
        sim.wait(tt)
        signal_3(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,180*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx+0.05)--fall 28
        sim.setJointTargetPosition(joint02,setpy-0.05)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h2)
        sim.wait(tt)
        signal_4(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,240*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx+0.05)--fall 29
        sim.setJointTargetPosition(joint02,setpy+0.05)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h2)
        sim.wait(tt)
        signal_5(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,300*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx)--fall 30
        sim.setJointTargetPosition(joint02,setpy)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h1)
        sim.wait(tt)
        signal_6(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        ----------------------------------------------
        sim.setJointTargetPosition(joint01,0) 
        sim.setJointTargetPosition(joint02,0)
        sim.wait(long_long_t)
        sim.setJointTargetPosition(jointr,0)
        sim.wait(long_long_t)
        -----------------------------------------------------------
        -----------------------------------------------------------
        pick_h1=0.07
        pick_h2=0.138
        pick_h3=0.2085
        pick_h4=0.2801
        setx=-0.5
        setpx=0.5
        signal_1(true)
        sim.setJointTargetPosition(joint01,setx) --pick_1
        sim.setJointTargetPosition(joint02,sety)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h1)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,60*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx+0.05) --pick_2 h2-h2-
        sim.setJointTargetPosition(joint02,sety-0.05)
        sim.wait(tt)
        signal_2(true)
        sim.setJointTargetPosition(joint03,aty-pick_h2)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,120*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx+0.05) --pick_3
        sim.setJointTargetPosition(joint02,sety+0.05)
        sim.wait(tt)
        signal_3(true)
        sim.setJointTargetPosition(joint03,aty-pick_h2)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,180*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx-0.05) --pick_4
        sim.setJointTargetPosition(joint02,sety+0.05)
        sim.wait(tt)
        signal_4(true)
        sim.setJointTargetPosition(joint03,aty-pick_h2)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,240*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx-0.05) --pick_5
        sim.setJointTargetPosition(joint02,sety-0.05)
        sim.wait(tt)
        signal_5(true)
        sim.setJointTargetPosition(joint03,aty-pick_h2)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,300*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx+0.1) --pick_6 h3-h3
        sim.setJointTargetPosition(joint02,sety+0.1)
        sim.wait(tt)
        signal_6(true)
        sim.setJointTargetPosition(joint03,aty-pick_h3)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,0)
        sim.wait(long_t)
        -----------------------------------------------------------
        sim.setJointTargetPosition(joint01,setpx-0.15)--fall 1
        sim.wait(tt)
        sim.setJointTargetPosition(joint02,setpy+0.15)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4)
        sim.wait(tt)
        signal_1(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4_up)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,60*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx-0.15)--fall 2
        sim.setJointTargetPosition(joint02,setpy+0.05)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4)
        sim.wait(tt)
        signal_2(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4_up)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,120*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx-0.15)--fall 3
        sim.setJointTargetPosition(joint02,setpy-0.05)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4)
        sim.wait(tt)
        signal_3(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4_up)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,180*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx-0.15)--fall 4
        sim.setJointTargetPosition(joint02,setpy-0.15)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4)
        sim.wait(tt)
        signal_4(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4_up)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,240*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx-0.05)--fall 5
        sim.setJointTargetPosition(joint02,setpy-0.15)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4)
        sim.wait(tt)
        signal_5(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4_up)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,300*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx-0.05)--fall 6
        sim.setJointTargetPosition(joint02,setpy-0.05)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4)
        sim.wait(tt)
        signal_6(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx) 
        sim.setJointTargetPosition(joint02,sety)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,0*math.pi/180)
        -----------------------------------------------------------
        sim.setJointTargetPosition(joint01,setx+0.1) --pick_7
        sim.setJointTargetPosition(joint02,sety)
        signal_1(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h3)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,60*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx+0.1) --pick_8
        sim.setJointTargetPosition(joint02,sety-0.1)
        signal_2(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h3)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,120*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx) --pick_9
        sim.setJointTargetPosition(joint02,sety-0.1)
        signal_3(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h3)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,180*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx) --pick_10
        sim.setJointTargetPosition(joint02,sety)
        signal_4(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h3)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,240*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx) --pick_11
        sim.setJointTargetPosition(joint02,sety+0.1)
        signal_5(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h3)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,300*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx-0.1) --pick_12
        sim.setJointTargetPosition(joint02,sety+0.1)
        signal_6(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h3)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,0)
        sim.wait(long_t)
         -----------------------------------------------------------
        sim.setJointTargetPosition(joint01,setpx-0.05)--fall 7
        sim.wait(tt)
        sim.setJointTargetPosition(joint02,setpy+0.05)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4)
        sim.wait(tt)
        signal_1(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4_up)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,60*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx-0.05)--fall 8
        sim.setJointTargetPosition(joint02,setpy+0.15)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4)
        sim.wait(tt)
        signal_2(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-0.12)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,120*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx+0.05)--fall 9
        sim.setJointTargetPosition(joint02,setpy+0.15)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4)
        sim.wait(tt)
        signal_3(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4_up)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,180*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx+0.05)--fall 10
        sim.setJointTargetPosition(joint02,setpy+0.05)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4)
        sim.wait(tt)
        signal_4(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4_up)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,240*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx+0.05)--fall 11
        sim.setJointTargetPosition(joint02,setpy-0.05)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4)
        sim.wait(tt)
        signal_5(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4_up)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,300*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx+0.05)--fall 12
        sim.setJointTargetPosition(joint02,setpy-0.15)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4)
        sim.wait(tt)
        signal_6(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx) 
        sim.setJointTargetPosition(joint02,sety)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,0)
        -----------------------------------------------------------
        sim.setJointTargetPosition(joint01,setx-0.1) --pick_13
        sim.setJointTargetPosition(joint02,sety)
        signal_1(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h3)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,60*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx-0.1) --pick_14 
        sim.setJointTargetPosition(joint02,sety-0.1)
        signal_2(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h3)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,120*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx-0.15) --pick_15 --h4-h4
        sim.setJointTargetPosition(joint02,sety+0.15)
        signal_3(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h4)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,180*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx-0.15) --pick_16
        sim.setJointTargetPosition(joint02,sety+0.05)
        signal_4(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h4)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,240*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx-0.15) --pick_17
        sim.setJointTargetPosition(joint02,sety-0.05)
        signal_5(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h4)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,300*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx-0.15) --pick_18
        sim.setJointTargetPosition(joint02,sety-0.15)
        signal_6(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h4)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,0)
        sim.wait(long_long_t)
        
         -----------------------------------------------------------
        sim.setJointTargetPosition(joint01,setpx+0.15)--fall 13
        sim.wait(long_long_t)
        sim.setJointTargetPosition(joint02,setpy-0.15)
        sim.wait(long_long_t)
        sim.setJointTargetPosition(joint03,aty-fall_h4)
        sim.wait(tt)
        signal_1(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4_up)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,60*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx+0.15)--fall 14
        sim.setJointTargetPosition(joint02,setpy-0.05)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4)
        sim.wait(tt)
        signal_2(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4_up)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,120*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx+0.15)--fall 15
        sim.setJointTargetPosition(joint02,setpy+0.05)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4)
        sim.wait(tt)
        signal_3(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4_up)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,180*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx+0.15)--fall 16
        sim.setJointTargetPosition(joint02,setpy+0.15)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4)
        sim.wait(tt)
        signal_4(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h4_up)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,240*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx+0.1)--fall 17 h3--h3
        sim.setJointTargetPosition(joint02,setpy-0.1)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h3)
        sim.wait(tt)
        signal_5(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h3_up)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,300*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx+0.1)--fall 18
        sim.setJointTargetPosition(joint02,setpy-0)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h3)
        sim.wait(tt)
        signal_6(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx) 
        sim.setJointTargetPosition(joint02,sety)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,0)
        -----------------------------------------------------------
        sim.setJointTargetPosition(joint01,setx-0.05) --pick_19
        sim.setJointTargetPosition(joint02,sety-0.15)
        signal_1(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h4)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,60*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx-0.05) --pick_20 
        sim.setJointTargetPosition(joint02,sety-0.05)
        signal_2(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h4)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,120*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx-0.05) --pick_21
        sim.setJointTargetPosition(joint02,sety+0.05)
        signal_3(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h4)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,180*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx-0.05) --pick_22
        sim.setJointTargetPosition(joint02,sety+0.15)
        signal_4(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h4)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,240*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx+0.05) --pick_23
        sim.setJointTargetPosition(joint02,sety+0.15)
        signal_5(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h4)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,300*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx+0.05) --pick_24
        sim.setJointTargetPosition(joint02,sety+0.05)
        signal_6(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h4)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,0)
        sim.wait(tt)
        sim.wait(long_t)
         -----------------------------------------------------------
        sim.setJointTargetPosition(joint01,setpx+0.1)--fall 19
        sim.wait(tt)
        sim.setJointTargetPosition(joint02,setpy+0.1)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h3)
        sim.wait(tt)
        signal_1(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h3_up)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,60*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx)--fall 20
        sim.setJointTargetPosition(joint02,setpy+0.1)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h3)
        sim.wait(tt)
        signal_2(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h3_up)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,120*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx)--fall 21
        sim.setJointTargetPosition(joint02,setpy)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h3)
        sim.wait(tt)
        signal_3(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h3_up)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,180*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx)--fall 22
        sim.setJointTargetPosition(joint02,setpy-0.1)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h3)
        sim.wait(tt)
        signal_4(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h3_up)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,240*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx-0.1)--fall 23
        sim.setJointTargetPosition(joint02,setpy-0.1)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h3)
        sim.wait(tt)
        signal_5(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h3_up)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,300*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx-0.1)--fall 24
        sim.setJointTargetPosition(joint02,setpy-0)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h3)
        sim.wait(tt)
        signal_6(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx) 
        sim.setJointTargetPosition(joint02,sety)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,0)
        -----------------------------------------------------------
        sim.setJointTargetPosition(joint01,setx+0.05) --pick_25
        sim.setJointTargetPosition(joint02,sety-0.05)
        signal_1(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h4)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,60*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx+0.05) --pick_26 
        sim.setJointTargetPosition(joint02,sety-0.15)
        signal_2(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h4)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,120*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx+0.15) --pick_27
        sim.setJointTargetPosition(joint02,sety-0.15)
        signal_3(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h4)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,180*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx+0.15) --pick_28
        sim.setJointTargetPosition(joint02,sety-0.05)
        signal_4(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h4)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,240*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx+0.15) --pick_29
        sim.setJointTargetPosition(joint02,sety+0.05)
        signal_5(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h4)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,300*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setx+0.15) --pick_30
        sim.setJointTargetPosition(joint02,sety+0.15)
        signal_6(true)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-pick_h4)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,0*math.pi/180)
        sim.wait(tt)
        sim.wait(long_long_t)
         -----------------------------------------------------------
        sim.setJointTargetPosition(joint01,setpx-0.1)--fall 25
        sim.wait(long_long_t)
        sim.setJointTargetPosition(joint02,setpy+0.1)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h3)
        sim.wait(tt)
        signal_1(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h3_up)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,60*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx-0.05)--fall 26
        sim.setJointTargetPosition(joint02,setpy+0.05)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h2)
        sim.wait(tt)
        signal_2(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,120*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx-0.05)--fall 27
        sim.setJointTargetPosition(joint02,setpy-0.05)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h2)
        sim.wait(tt)
        signal_3(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,180*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx+0.05)--fall 28
        sim.setJointTargetPosition(joint02,setpy-0.05)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h2)
        sim.wait(tt)
        signal_4(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,240*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx+0.05)--fall 29
        sim.setJointTargetPosition(joint02,setpy+0.05)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h2)
        sim.wait(tt)
        signal_5(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        sim.setJointTargetPosition(jointr,300*math.pi/180)
        sim.wait(tt)
        sim.setJointTargetPosition(joint01,setpx)--fall 30
        sim.setJointTargetPosition(joint02,setpy)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty-fall_h1)
        sim.wait(tt)
        signal_6(false)
        sim.wait(tt)
        sim.setJointTargetPosition(joint03,aty)
        sim.wait(tt)
        ----------------------------------------------
        sim.setJointTargetPosition(joint01,0) 
        sim.setJointTargetPosition(joint02,0)
        setx=0.485
        setpx=-0.515
        pick_h1=0.07
        pick_h2=0.139
        pick_h3=0.207
        pick_h4=0.2772
        sim.wait(long_long_t)
        sim.setJointTargetPosition(jointr,0*math.pi/180)
        sim.wait(long_long_t)
    -----------------------------------------------------------
    end
end

function sysCall_cleanup()
    -- Put some clean-up code here
end
